name: default
on:
  push:
    branches: master
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          name: cryptorelay
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use cryptorelay
        if: github.ref != 'refs/heads/master'

      - name: Build and test
        run: nix-build

      - name: Publish docker image
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
          nix-build docker.nix
          OUTPUT=$(docker load < result)
          IMAGE=${OUTPUT#Loaded image: }
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            TAG="latest"
          else
            TAG=${GITHUB_REF#refs/tags/}
          fi
          TARGET="docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:$TAG"
          docker tag $IMAGE $TARGET
          docker push $TARGET
          echo "pushed: $TARGET"
