name: default
on:
  push:
    branches: master
    tags:
    - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Use cachix
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use cryptorelay

      - name: Lint with flake8
        run: nix-shell -E "$SHELL" --run "$CMD"
        env:
          SHELL: "with import <nixpkgs> {}; mkShell { buildInputs = [ (import ./integration_tests { inherit pkgs; }) ]; }"
          CMD: "flake8 --show-source --count --statistics --format='::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s'"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v6
        if: github.ref == 'refs/heads/master'
        with:
          name: cryptorelay
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use cryptorelay
        if: github.ref != 'refs/heads/master'

      - name: Build and test
        run: nix-shell --run pytest

      - name: Publish docker image
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin
          nix-build docker.nix
          OUTPUT=$(docker load < result)
          IMAGE=${OUTPUT#Loaded image: }
          if [[ "$GITHUB_REF" = "refs/tags/"* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG="latest"
          fi
          TARGET="docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:$TAG"
          docker tag $IMAGE $TARGET
          docker push $TARGET
          echo "pushed: $TARGET"
